### ISSUE TITLE
Exporter must export float values for all stats

### ISSUE THREAD

**Issue by naveen-krishnaprasad** [gdvalle/trafficserver_exporter#1]
I tried the trafficserver_exporter against Apache Traffic Server 7.1.1. There seems to be an error with some stats that are exported as strings. There are some zero value stats which are passed in as strings, and that breaks the Prometheus client (perhaps it worked ok for older versions of the clients).

Also, its worth noting that older versions of Apache traffic server < 5.2.x do not emit numeric values. So we need an explicit conversion to float within the exporter.

In the absence of this change, one would see an error from the Prometheus client that looks like:

Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "build/bdist.linux-x86_64/egg/prometheus_client/exposition.py", line 86, in do_GET
    output = generate_latest(registry)
  File "build/bdist.linux-x86_64/egg/prometheus_client/exposition.py", line 75, in generate_latest
    output.append('{0}{1} {2}\n'.format(name, labelstr, core._floatToGoString(value)))
  File "build/bdist.linux-x86_64/egg/prometheus_client/core.py", line 800, in _floatToGoString
    elif math.isnan(d):
TypeError: a float is required

The fix is to use float values for the zero labels, and optionally explicitly convert the stats to float if required.

**Comment by gdvalle** [comment]
Fixed in https://github.com/gdvalle/trafficserver_exporter/pull/7
Thank you much for the report!
