### ISSUE TITLE
Run trafficserver_exporter error

### ISSUE THREAD

**Issue by huy-vt** [gdvalle/trafficserver_exporter#10]
I have one problem is running running export as following:
[root@localhost trafficserver_exporter-0.0.2]# trafficserver_exporter -vv --endpoint=http://cdn.ats.xxx/_stats
DEBUG:trafficserver_exporter.trafficserver_exporter:Starting HTTP server
DEBUG:trafficserver_exporter.trafficserver_exporter:Registering StatsPluginCollector
DEBUG:trafficserver_exporter.collector:Beginning collection
DEBUG:trafficserver_exporter.collector:Fetching JSON: http://cdn.ats.xxx/_stats
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): cdn.ats.xxx:80
DEBUG:urllib3.connectionpool:http://cdn.ats.xxx:80 "GET /_stats HTTP/1.1" 200 None
DEBUG:trafficserver_exporter.collector:Gathering metrics
Traceback (most recent call last):
  File "/bin/trafficserver_exporter", line 9, in <module>
    load_entry_point('trafficserver-exporter==0.0.2', 'console_scripts', 'trafficserver_exporter')()
  File "build/bdist.linux-x86_64/egg/trafficserver_exporter/trafficserver_exporter.py", line 75, in main
  File "build/bdist.linux-x86_64/egg/prometheus_client/core.py", line 49, in register
  File "build/bdist.linux-x86_64/egg/prometheus_client/core.py", line 86, in _get_names
  File "build/bdist.linux-x86_64/egg/trafficserver_exporter/collector.py", line 54, in collect
  File "build/bdist.linux-x86_64/egg/trafficserver_exporter/collector.py", line 265, in parse_metrics
KeyError: 'proxy.process.http.transaction_totaltime.errors.unclassified'

i don't know fix , please help me !

**Comment by gdvalle** [comment]
Thanks for the bug report @j0k3r2k17!

Could you provide me your trafficserver version, and the output of the `/_stats` endpoint?

**Comment by huy-vt** [comment]
Hello @gdvalle this is trafficserver version and output of the /_status 
https://www.pastiebin.com/5b2c7868580c3

**Comment by gdvalle** [comment]
Thanks @j0k3r2k17!  I added your stats JSON to the tests and fixed this in https://github.com/gdvalle/trafficserver_exporter/commit/86b60226aa963cebf0fe3b13714f3ac4125e563d.

Let me know if you encounter any more issues!
