### ISSUE TITLE
Collector should cope with cache volumes missing

### ISSUE THREAD

**Issue by naveen-krishnaprasad** [gdvalle/trafficserver_exporter#2]
Cache volumes can be missing from the Apache traffic server stats (this can be controlled via config). But the collector does not cope with this very well. 

Traceback (most recent call last):
  File "/usr/bin/trafficserver_exporter", line 9, in <module>
    load_entry_point('trafficserver-exporter==0.0.1', 'console_scripts', 'trafficserver_exporter')()
  File "build/bdist.linux-x86_64/egg/trafficserver_exporter/trafficserver_exporter.py", line 61, in main
  File "build/bdist.linux-x86_64/egg/prometheus_client/core.py", line 50, in register
  File "build/bdist.linux-x86_64/egg/prometheus_client/core.py", line 86, in _get_names
  File "build/bdist.linux-x86_64/egg/trafficserver_exporter/collector.py", line 45, in collect
  File "build/bdist.linux-x86_64/egg/trafficserver_exporter/collector.py", line 486, in parse_metrics
UnboundLocalError: local variable 'volume' referenced before assignment

Submitting an (minor) issue to fix this, a check required to make sure we have volumes.

**Comment by gdvalle** [comment]
Thank you for the report!  Fixed in https://github.com/gdvalle/trafficserver_exporter/pull/8.

Please re-open if you still have issues!
